### PR TITLE
fix #2869, add MultilineTextConverter in case of multiline results

### LINKED ISSUE #2869: Preview for ResultListBox is broken
1. no preview for ResultListBox.xaml using visual studio design.

image

2. no preview for `ResultListBox` in `MainWindow.xaml` using visual studio design.
image

2. no preview for `ResultListBox` in `SettingWindow.xaml` using visual studio design.
image

3. no preview for Result Item in `Theme` tab from `Wox Settings` window.
image

We have no idea how to fix this, We would appreciate it if anyone could fix this.

### PR DESCRIPTION
**Pull request by sausagemountain**

### CODE REVIEW

**Comment by sausagemountain** [comment]
Multiline fix is for this, which I did not think was possible
Multiline text

**Review by bao-qian — CHANGES_REQUESTED** [review]
1. I confirm the settings page is fixed, but the icon is wrong.
image

2. but the vs design issue is still exist, could you take a look?

e.g. 
image

File: Wox/Converters/MultilineTextConverter.cs [hunk 1]
```diff
@@ -0,0 +1,25 @@
...
+using System.Windows.Data;
+
+namespace Wox.Converters
+{
+    class MultilineTextConverter: IValueConverter
+    {
+        /// <inheritdoc />
+        public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
+        {
+            return (value as string).Replace("\n", "\u2007");
```
Comment (bao-qian) [inline Wox/Converters/MultilineTextConverter.cs]: need null check
```
Exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Wox.Converters.MultilineTextConverter.Convert(Object value, Type targetType, Object parameter, CultureInfo culture) in C:\projects\wox\Wox\Converters\MultilineTextConverter.cs:line 16
   at System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
   at System.Windows.Data.BindingExpression.Activate(Object item)
   at System.Windows.Data.BindingExpression.OnDataContextChanged(DependencyObject contextElement)

```

**Review by bao-qian — CHANGES_REQUESTED** [review]
